#!/bin/zsh

function submodule_init() {
  git submodule update --init --recursive
  local submodules=()
  while IFS= read -r line; do
    submodules+=(${${${line#* }#* }%% *})
  done < <(git submodule)

  local p=$PWD
  for i in $submodules; do
    [ ! -d $p/$i ] && continue
    cd $p/$i
    echo "----------\n$i"
    git checkout master
  done
  echo '----------'
}

function lua_build() {
  cd personal/lua-language-server
  cd 3rd/luamake
  ./compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
}

function generate_uninstaller() {
  local setup=$(cat setup)
  echo ${setup//--restow/--delete} > uninstall
}

function mac_setup() {
  defaults write -g InitialKeyRepeat -int 16 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)

  # enable dock hiding
  defaults write com.apple.dock autohide -bool true

  # set dock size
  defaults write com.apple.dock tilesize -int 1

  # disable dock icon bounce
  defaults write com.apple.dock no-bouncing -bool false

  # lock dock size
  defaults write com.apple.Dock size-immutable -bool yes && \

  # move dock to the left
  defaults write com.apple.dock orientation left

  killall Dock

  # show hidden files in finder
  defaults write com.apple.finder AppleShowAllFiles true

  # show the hidden library directory in finder
  chflags nohidden ~/Library

  # disable rubber band scrolling
  defaults write -g NSScrollViewRubberbanding -bool false
}

function brew_clutch() {
  echo "eval \"\$(/opt/homebrew/bin/brew shellenv)\"" > $HOME/.zprofile
}

function help_text() {
cat <<EOF
Possible arguments
  --sub, -S    submodule_init
  --lua, -L    lua_build
  --gen, -G    generate_uninstaller
  --mac, -M    mac_setup
  --brew, -B   brew_clutch
EOF
}
case $1 in
  "--sub"|"-S") submodule_init;;
  "--lua"|"-L") lua_build;;
  "--gen"|"-G") generate_uninstaller;;
  "--mac"|"-M") mac_setup;;
  "--brew"|"-B") brew_clutch;;
  "") help_text;;
esac
