#!/bin/zsh

function submodule_init() {
  git submodule update --init --recursive
  local submodules=()
  while IFS= read -r line; do
    submodules+=(${${${line#* }#* }%% *})
  done < <(git submodule)

  local p=$PWD
  for i in $submodules; do
    [ ! -d $p/$i ] && continue
    cd $p/$i
    echo "----------\n$i"
    git checkout master
  done
  echo '----------'
}

function lua_build() {
  local LUA_SRC=$HOME/.local/src
  mkdir -p $LUA_SRC
  cd $LUA_SRC
  rm -rf lua-language-server
  git clone git@github.com:sumneko/lua-language-server.git
  cd lua-language-server
  git submodule update --init --recursive
  cd 3rd/luamake
  ./compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
}

function generate_uninstaller() {
  local setup=$(cat setup)
  echo ${setup//--restow/--delete} > uninstall
}

function mac_setup() {
  defaults write -g InitialKeyRepeat -int 16 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)

  # enable dock hiding
  defaults write com.apple.dock autohide -bool true

  # set dock size
  defaults write com.apple.dock tilesize -int 32

  # disable dock icon bounce
  defaults write com.apple.dock no-bouncing -bool false

  # lock dock size
  defaults write com.apple.Dock size-immutable -bool yes && \

  # move dock to the left
  # defaults write com.apple.dock orientation left

  # change dock appearance delay
  # defaults write com.apple.Dock autohide-delay -float 1
  
  # reset dock appearance delay
  # defaults delete com.apple.Dock autohide-delay

  killall Dock

  # show hidden files in finder
  defaults write com.apple.finder AppleShowAllFiles true

  # show the hidden library directory in finder
  chflags nohidden ~/Library

  # disable rubber band scrolling
  defaults write -g NSScrollViewRubberbanding -bool false

  # disable Cmd-H hiding apps by making it Hypr-H
  # local apps=(
  #   Spotify
  #   Safari
  #   kitty
  #   Telegram
  # )
  #
  # for key value in ${(kv)apps}; do
  #   local bundle=$(mdls -name kMDItemCFBundleIdentifier -raw /Applications/$key.app)
  #   defaults write $bundle NSUserKeyEquivalents -dict "Hide $key" "\@\~\^\$y"
  # done
}

function brew_clutch() {
  echo "eval \"\$(/opt/homebrew/bin/brew shellenv)\"" > $HOME/.zprofile
}

function help_text() {
cat <<EOF
Possible arguments
  --sub, -S    submodule_init
  --lua, -L    lua_build
  --gen, -G    generate_uninstaller
  --mac, -M    mac_setup
  --brew, -B   brew_clutch
EOF
}
case $1 in
  "--sub"|"-S") submodule_init;;
  "--lua"|"-L") lua_build;;
  "--gen"|"-G") generate_uninstaller;;
  "--mac"|"-M") mac_setup;;
  "--brew"|"-B") brew_clutch;;
  "") help_text;;
esac
