#!/usr/bin/env zsh

local dots=(vim)
local submodules=(nvim zsh personal raspberry-pi)

local stow_folders=($dots $submodules)

for folder in ${stow_folders}; do
  stow --restow \
    --override=.ssh \
    --override=.config/zsh/prompt \
    --target=$HOME $folder
done
