#!/usr/bin/env zsh

case $1 in
  "--pi")
    local dots=(vim)
    local submodules=(nvim zsh personal raspberry-pi);;
  *)
    local dots=(alacritty kitty xbar vim)
    local submodules=(nvim zsh pass personal);;
esac

local stow_folders=($dots $submodules)

for folder in ${stow_folders}; do
  stow --restow \
    --override=.ssh \
    --override=.config/zsh/prompt \
    --override=.config/zsh/nav \
    --override=.zshrc \
    --target=$HOME $folder
done
