#!/usr/bin/env bash

# run this script to install stuff with stow
# run it with a -D flag to uninstall stuff

stow_list=(zsh kitty pass alacritty)
nvim_list=(nvim personal)

del=false
[ $1 ] && [ $1 = "-D" ] && del=true

for i in ${stow_list[@]}; do
  stow -D --target $HOME $i
  [[ $del = false ]] && stow --target $HOME $i || continue
done

# NVIM_RUNTIMEPATH=$HOME/.config/nvim
 
# rm -rf $NVIM_RUNTIMEPATH
# if [[ $del = false ]]; then
#   curl -fLo $NVIM_RUNTIMEPATH/autoload/plug.vim --create-dirs \
#     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi

for i in ${nvim_list[@]}; do
  stow -D --target $HOME $i
  [[ $del = false ]] && stow --target $HOME $i || continue
done
