#!/bin/zsh

git submodule update --init --recursive
repo_folders=(
  zsh
  walls
  pass/.password-store
  nvim/.config/nvim
  personal
)

p=$PWD
for i in $repo_folders; do
  if [ -d $p/$i ]; then
    cd $p/$i
    echo "----------\n$i"
    git checkout master
  fi
done
echo '----------'
