#!/usr/bin/env zsh

local dots=(tmux nvim term vim xbar zsh)
local root=()
local submodules=(personal)

setopt nullglob
local clear_list=(
  $HOME/.zshenv
  $HOME/.zsh_history
  $HOME/.zprofile
)

local stow_folders=($dots $submodules)

for file in ${clear_list}; do
  rm -rf $file
done

for folder in ${stow_folders}; do
  stow --delete \
    --override=.ssh \
    --override=.config/zsh/prompt \
    --override=.config/zsh/nav \
    --target=$HOME $folder
done

for folder in ${root}; do
  sudo stow --delete \
    --target=/ $folder
done
