#!/usr/bin/env zsh

local dots=(alacritty kitty xbar)
local submodules=(nvim zsh pass personal)

local stow_folders=($dots $submodules)

for folder in ${stow_folders}; do
  stow --delete --target=$HOME $folder
done
