#!/usr/bin/env zsh

local dots=(tmux mac nvim term vim xbar zsh)
local root=()
local submodules=(personal)

setopt nullglob
local clear_list=(
  $HOME/.zsh*
  $HOME/.zprofile
)

local stow_folders=($dots $submodules)

for folder in ${stow_folders}; do
  stow --delete \
    --override=.ssh \
    --override=.config/zsh/prompt \
    --override=.config/zsh/nav \
    --override=.zshrc \
    --target=$HOME $folder
done

for folder in ${root}; do
  sudo stow --delete \
    --target=/ $folder
done

for file in ${clear_list}; do
  rm -rf $file
done
