#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
LOGFILE=$SCRIPT_DIR/zathura.log

Z_INDEX=
Z_INDEX+=" -d /home/khang/uni"
Z_INDEX+=" -d /home/khang/repos/books"
Z_INDEX+=" -d /home/khang/repos/tex"
Z_INDEX+=" -d /home/khang/repos/hire"

zathura_open() {
  nohup zathura "$1" </dev/null >/dev/null 2>&1 &
}
PATH=/home/khang/.cargo/bin:$PATH
export PATH

if [ -z "$1" ]; then
  zathura-pdf-index ls $Z_INDEX
else
  TARGET=$(zathura-pdf-index resolve $Z_INDEX -q "$1")
  if [ $? = 0 ]; then
    zathura_open "$TARGET"
  fi
  # echo "$TARGET" >>$LOGFILE
fi
