//
//  charmap.swift
//  intuous
//
//  Created by khang on 22/2/23.
//

import Cocoa
import Foundation

let lowercaseCharMap: [Character: KeyCode] = [
    "a": .a,
    "b": .b,
    "c": .c,
    "d": .d,
    "e": .e,
    "f": .f,
    "g": .g,
    "h": .h,
    "i": .i,
    "j": .j,
    "k": .k,
    "l": .l,
    "m": .m,
    "n": .n,
    "o": .o,
    "p": .p,
    "q": .q,
    "r": .r,
    "s": .s,
    "t": .t,
    "u": .u,
    "v": .v,
    "w": .w,
    "x": .x,
    "y": .y,
    "z": .z,
    "0": .zero,
    "1": .one,
    "2": .two,
    "3": .three,
    "4": .four,
    "5": .five,
    "6": .six,
    "7": .seven,
    "8": .eight,
    "9": .nine,
    "=": .equals,
    "-": .minus,
    ";": .semicolon,
    "'": .apostrophe,
    ",": .comma,
    ".": .period,
    "/": .forwardSlash,
    "\\": .backslash,
    "`": .grave,
    "[": .leftBracket,
    "]": .rightBracket,
    " ": .space
]

let uppercaseCharMap: [Character: KeyCode] = [
    "A": .a,
    "B": .b,
    "C": .c,
    "D": .d,
    "E": .e,
    "F": .f,
    "G": .g,
    "H": .h,
    "I": .i,
    "J": .j,
    "K": .k,
    "L": .l,
    "M": .m,
    "N": .n,
    "O": .o,
    "P": .p,
    "Q": .q,
    "R": .r,
    "S": .s,
    "T": .t,
    "U": .u,
    "V": .v,
    "W": .w,
    "X": .x,
    "Y": .y,
    "Z": .z,
    ")": .zero,
    "!": .one,
    "@": .two,
    "#": .three,
    "$": .four,
    "%": .five,
    "^": .six,
    "&": .seven,
    "*": .eight,
    "(": .nine,
    "+": .equals,
    "_": .minus,
    ":": .semicolon,
    "\"": .apostrophe,
    "<": .comma,
    ">": .period,
    "?": .forwardSlash,
    "|": .backslash,
    "~": .grave,
    "{": .leftBracket,
    "}": .rightBracket
]
