#!/usr/bin/env zsh

function ed() {
  typeset -A local marks=(
    [.]="$ZSH_DOTS/edits"
    [a]="$HOME/.config/ags/scanlist"
    [al]="$HOME/.config/alacritty/alacritty.yml"
    [g]="$HOME/.config/git/config"
    [k]="$DOTS/term/.config/kitty/kitty.conf"
    [t]="$DOTS/tmux/.config/tmux/tmux.conf"
    [n]="$DOTS/zsh/.config/zsh/nav"
    [v]="$DOTS/nvim/.config/nvim/init.lua"
    [z]="$DOTS/zsh/.config/zsh/.zshrc"
  )
  function fuzzy_ed() {
    # pick a key out of the keys of pretty
    local key=$(for i in ${(v)marks}; do
      echo "${i/$HOME\//~/}"
    done | fzf $FZF_OPTS)
    [ -z $key ] && return true
    $EDITOR "${key/\~\//$HOME/}"
  }

  # if no first arg supplied, run fuzzy_ed
  [ -z $1 ] && fuzzy_ed && return true
 
  local file=$marks[$1]
  [ -z $file ] && echo "nothing happened." && return true
  $EDITOR $file
}
