#!/usr/bin/env zsh


function ed() {
  typeset -A local marks=(
    [.]="$ZSH_DOTS/edits"
    [a]="$HOME/.config/ags/scanlist"
    [al]="$HOME/.config/alacritty/alacritty.yml"
    [g]="$HOME/.config/git/config"
    [k]="$DOTS/term/.config/kitty/kitty.conf"
    [s]="$HOME/.config/skhd/skhdrc"
    [t]="$DOTS/tmux/.config/tmux/tmux.conf"
    [n]="$DOTS/zsh/.config/zsh/nav"
    [v]="$DOTS/nvim/.config/nvim/init.lua"
    [y]="$HOME/.config/yabai/yabairc"
    [z]="$DOTS/zsh/.config/zsh/.zshrc"
  )

  local quit() {
    echo "nothing happened."
    return 0
  }
  local not_found() {
    echo "target not indexed."
    return 0
  }

  local list_dest() {
    # replace $HOME with ~ in fzf
    for i in ${(v)marks}; do
      echo "${i/$HOME\//~/}"
    done
  }

  local fuzzy_ed() {
    # fzf over a list of destination directories
    local key=$(list_dest | fzf $FZF_OPTS)
    [ -z $key ] && quit && return 0 # do nothing if nothing is selected
    $EDITOR "${key/\~\//$HOME/}" # replace ~ with $HOME
  }

  # if no first arg supplied, run fuzzy_ed
  [ -z $1 ] && fuzzy_ed && return 0
 
  local file=$marks[$1]
  [ -z $file ] && not_found && return 0
  $EDITOR $file
}
