#!/usr/bin/env zsh

# command flag autocomplete
# autoload -U compinit; compinit

# include hidden dir tab complete
setopt globdots

# fuzzy vim
function v() {
  local target=$(fzf $FZF_OPTS)
  [ $target ] && $EDITOR $target
}
