#!/usr/bin/env zsh

# generic navigation
# g for jump
# requires fd
function g() {
  local depth=4
  # if directory has no children directory, end
  local check=$(command ls -Ap)
  [[ ! $check = *"/"* ]] && return true

  local target=$(fd --hidden -d $depth -t d | fzf \
    --height=10 +m \
    --no-mouse \
    --header=${PWD/#$HOME/'~'} \
    --expect "enter,esc,left,right" \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')
  target=${target#/*}

  local res=()
  while IFS= read -r line; do
    res+=( "$line" )
  done < <( echo $target )

  local key=${res[1]}
  local location=${res[2]}

  case $key in
    'esc') return true ;;
    'left') cd ../ && g ;;
    'right') cd $location && g;;
    'enter') cd $location ;;
    *) return true ;;
  esac
  unset key
}
