#!/usr/bin/env zsh

# generic navigation
# g for jump
# requires fd
g() {
  local dir list fuzzy

  # if directory has no children directory, end
  [[ ! $(command ls -Ap) = *"/"* ]] && return

  list=(fd -H -I -c never -d 4 -t d --strip-cwd-prefix
    -E ".git")

  fuzzy=(fzf $FZF_OPTS
    --header=${PWD/$HOME/'~'}
    --expect "esc,left,enter,right")

  [[ $($list | $fuzzy) =~ '^(.*)'$'\n''(.*)$' ]]

  case ${match[1]} in
  'esc') return ;;
  'left') cd .. && g ;;
  'enter') [ -d ${match[2]} ] && cd ${match[2]} ;;
  'right') [ -d ${match[2]} ] && cd ${match[2]} && g ;;
  *) return ;;
  esac
}
