#!/usr/bin/env zsh

# listing files
alias ls="exa -a --group-directories-first --ignore-glob='.DS_Store'"
alias ll="exa -al --group-directories-first --ignore-glob='.DS_Store'"

# file tree
function lt() {
  # usage: lt <depth> <directory>
  # <depth> is optional, defaults to 2.
  # <directory> is optional, defaults to $PWD.
  [ -d $1 ] && [ -z $2 ] \
    && exa -a --tree --level=2 -- $1 \
    || exa -a --tree --level=${1-2} -- ${2-.}
}
