#!/usr/bin/env zsh

# listing files
EXA_OPTS=(
  --group-directories-first
  --sort=Filename
  --ignore-glob='.DS_Store'
)
alias ls="exa -a $EXA_OPTS"
alias ll="exa -al $EXA_OPTS"

# file tree
function lt() {
  # usage: lt <depth> <directory>
  # <depth> is optional, defaults to 2.
  # <directory> is optional, defaults to $PWD.
  [ -d $1 ] && [ -z $2 ] \
    && exa -a --tree --level=2 -- $1 \
    || exa -a --tree --level=${1-2} -- ${2-.}
}
