#!/usr/bin/env zsh

typeset -A local nav=(
  # [t]="$HOME/.config/nvim/plugged/telescope.nvim/lua/telescope"
  [A]="/Applications"
  [b]="$REPOS/blog/dev"
  [bo]="$REPOS/books"
  [c]="$REPOS/ci"
  [cf]="$HOME/.config"
  [d]="$DOTS"
  [e]="$HOME/expo-apps"
  [f]="$HOME/files"
  [h]="/opt/homebrew"
  [j]="$HOME/Downloads"
  [l]="$HOME/.local"
  [lb]="$HOME/.local/bin"
  [ls]="$HOME/.local/src"
  [m.]="/Applications/MultiMC.app/Data"
  [mc]="$HOME/.local/minecraft/server"
  [n]="$REPOS/notes"
  [o]="$HOME/other-repos"
  [p]="$DOTS/personal"
  [pl]="$HOME/.config/nvim/plugged"
  [pw]="$DOTS/personal/.password-store"
  [q.]="$HOME/.local/src/qmk_firmware"
  [q]="$DOTS/qmk"
  [v]="$DOTS/nvim/.config/nvim"
  [vl]="$DOTS/nvim/.config/nvim/lua/brew"
  [z]="$DOTS/zsh/.config/zsh"
)

function 2m() {
  local BASE=~/modtree
  local TARGET=$(head -n 1 $BASE/.work)
  local DEFAULT=$BASE/$TARGET
  local REMOTE=$(git remote get-url --push origin 2>/dev/null)
  local CORRECT="git@github.com:modtree/modtree.git"
  [[ $REMOTE != $CORRECT || $PWD == $BASE ]] && cd $DEFAULT 2>/dev/null && return 0
  local ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
  cd $DEFAULT 2>/dev/null || cd $BASE
}

for k dir in ${(kv)nav}; do
  [ ! -d $dir ] && echo "zsh nav: $dir doesn't exist" && continue
  alias 2$k="cd $dir"
done
unset nav k v

alias 2.="$EDITOR $ZSH_DOTS/nav"
alias o="cd .." # out
alias b="cd -"  # back
alias rep="cd $REPOS"

# goes to root of git repo
function 2r() { cd $(git rev-parse --show-toplevel) }

function jumpToFolder() {
  local BASEDIR=$1 
  local DEFAULTDIR=$2

  local OPTIONS=$(fd -t d -d 1 \
    --base-directory $BASEDIR \
    --exec basename)

  local RES="home\n$OPTIONS"

  local TARGET=$(echo $RES | fzf $FZF_OPTS)

  case $TARGET in 
    "") return true;;
    "home") cd $DEFAULTDIR;;
    *) cd $BASEDIR$TARGET;;
  esac
}

# to university folder
function 2u() {
  local BASEDIR=$REPOS/uni
  local DEFAULTDIR=$REPOS/uni

  local OPTIONS=$(fd -t d -d 1 \
    --base-directory $BASEDIR \
    --exec basename)

  local RES="home\n$OPTIONS"

  local TARGET=$(echo $RES | fzf $FZF_OPTS)

  function jumpToModule() {
    cd $BASEDIR/$TARGET/modules/$TARGET 2>/dev/null \
      || cd $BASEDIR/$TARGET/modules
  }

  case $TARGET in 
    "") return true;;
    "home") cd $DEFAULTDIR;;
    *) jumpToModule;;
  esac
}
