#!/usr/bin/env zsh

# aliases
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias monls="while; do; clear; ls; sleep 1; done" # monitor directory
alias monfile="tail -f" # monitor one file
alias montree="while; do; clear; exa --tree -L 2 -I node_modules; sleep 1; done" # monitor tree
alias si="$EDITOR .stow-local-ignore"
alias t="$EDITOR $REPOS/uni/todo.md"
alias ka="killall"
alias zb="time zsh -i -c exit" # zsh benchmark
alias zr="exec $SHELL -l" # reloads shell
alias rg="rg --hidden"
alias fd="fd --hidden"
alias py=python3
alias oc=octave
alias vim=nvim
alias pi="pip install"
alias qr="node ~/sunnus/qr-test/lib/index.js"

alias yb="yarn build"
alias yl="yarn lint"
alias yd="yarn dev"

# keybinds
bindkey "^[[3~" delete-char
bindkey '^[[Z' reverse-menu-complete

# really short functions

# fuzzy vim
v() {
  local target=$(fzf $FZF_OPTS)
  [ $target ] && $EDITOR $target
}
