#!/usr/bin/env zsh

# aliases
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias si="$EDITOR .stow-local-ignore"
alias t="$EDITOR $REPOS/uni/todo.md"
alias sr="brew services restart skhd" # skhd restart
alias yr="brew services restart yabai" # yabai restart
alias zb="time zsh -i -c exit" # zsh benchmark
alias zr="exec $SHELL -l" # reloads shell
alias rg="rg --hidden"
alias fd="fd --hidden"

alias py=python3
alias oc=octave
alias vim=nvim

alias yb="yarn build"
alias yd="yarn dev"

# keybinds
bindkey "^[[3~" delete-char
bindkey '^[[Z' reverse-menu-complete

# really short functions

# fuzzy vim
function v() {
  local target=$(fzf $FZF_OPTS)
  [ $target ] && $EDITOR $target
}
