#!/usr/bin/env zsh
#

alias tls="tmux ls"

function tkl() {
  if [ $1 ]; then
    tmux kill-session -t "$1"
  else
    echo "Please provide a session name."
    return 0
  fi
}

# function ta() {
#   local t="${1-base}"
#   local v=true
#   # first argument is target attach
#   # default value: "base"
# 
#   if [ -z "$TMUX" ]; then
#     # when outside of tmux
#     $v && echo "outside TMUX"
# 
#     if tmux has-session -t "$t" 2>/dev/null; then
#       # if target exists, attach to it 
#       $v && echo "session exists"
#       tmux attach -t $t; return
#     else
#       # else if target doesn't exist,
#       # just start a new session first
#       $v && echo "not existing, creating fresh"
#       tmux new-session -s $t -d; return
# 
#       # if launch script exists, use it
#       if [ -f $DOTS/tmux/$1.sh ]; then
#         $v && echo "launch script exists"
#         tmux send-keys -t $t "$DOTS/tmux/$1.sh" ENTER; return
#       else
#       fi
#     fi
#   else
#     # when inside of tmux
#     $v && echo "inside TMUX"
# 
#     if tmux has-session -t $t 2>/dev/null; then
#       # if target exists, switch to it
#       $v && echo "session exists"
#       tmux switch-client -t $t; return
#     else
#       # else if target doesn't exist,
#       # just start a new session first
#       $v && echo "not existing, creating fresh"
#       tmux new-session -As $t -d
#       tmux switch-client -t $t; return
# 
#       # if launch script exists, use it
#       if [ -f $DOTS/tmux/$1.sh ]; then
#         $v && echo "launch script exists"
#         tmux send-keys -t $t "$DOTS/tmux/$1.sh" ENTER; return
#       else
#       fi
#     fi
#   fi
# }

function spt() {
  ta "spt"
}
