#! /bin/sh
xrandr --output eDP1 --primary --mode 1440x900 --pos 240x1080 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
$HOME/.fehbg
