#!/bin/sh
#
# https://askubuntu.com/questions/1441271/how-do-you-disable-all-super-key-shortcuts-in-gnome

gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-10 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-2 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-3 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-4 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-5 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-6 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-7 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-8 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-9 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-1 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-10 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-2 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-3 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-4 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-5 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-6 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-7 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-8 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-9 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-1 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-10 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-2 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-3 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-4 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-5 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-6 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-7 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-8 []
gsettings set org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-9 []
gsettings set org.gnome.shell.keybindings open-new-window-application-1 []
gsettings set org.gnome.shell.keybindings open-new-window-application-2 []
gsettings set org.gnome.shell.keybindings open-new-window-application-3 []
gsettings set org.gnome.shell.keybindings open-new-window-application-4 []
gsettings set org.gnome.shell.keybindings open-new-window-application-5 []
gsettings set org.gnome.shell.keybindings open-new-window-application-6 []
gsettings set org.gnome.shell.keybindings open-new-window-application-7 []
gsettings set org.gnome.shell.keybindings open-new-window-application-8 []
gsettings set org.gnome.shell.keybindings open-new-window-application-9 []
gsettings set org.gnome.settings-daemon.plugins.media-keys rotate-video-lock-static []
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-toggle-static []
gsettings set org.gnome.mutter.keybindings switch-monitor []
gsettings set org.gnome.mutter overlay-key 'Super_R'


gsettings list-recursively | grep 'overlay'
# gsettings list-recursively
