local M = {}

M.extras = function(colors)
  return {
    -- nvim-cmp
    CmpItemAbbr = { link = 'GruvboxFg0' },
    CmpItemAbbrDeprecated = { link = 'GruvboxFg1' },
    CmpItemAbbrMatch = { link = 'GruvboxBlueBold' },
    CmpItemAbbrMatchFuzzy = { link = 'GruvboxBlueUnderline' },
    CmpItemMenu = { link = 'GruvboxGray' },
    CmpItemKindText = { link = 'GruvboxOrange' },
    CmpItemKindVariable = { link = 'GruvboxOrange' },
    CmpItemKindMethod = { link = 'GruvboxBlue' },
    CmpItemKindFunction = { link = 'GruvboxBlue' },
    CmpItemKindConstructor = { link = 'GruvboxYellow' },
    CmpItemKindUnit = { link = 'GruvboxBlue' },
    CmpItemKindField = { link = 'GruvboxBlue' },
    CmpItemKindClass = { link = 'GruvboxYellow' },
    CmpItemKindInterface = { link = 'GruvboxYellow' },
    CmpItemKindModule = { link = 'GruvboxBlue' },
    CmpItemKindProperty = { link = 'GruvboxBlue' },
    CmpItemKindValue = { link = 'GruvboxOrange' },
    CmpItemKindEnum = { link = 'GruvboxYellow' },
    CmpItemKindOperator = { link = 'GruvboxYellow' },
    CmpItemKindKeyword = { link = 'GruvboxPurple' },
    CmpItemKindEvent = { link = 'GruvboxPurple' },
    CmpItemKindReference = { link = 'GruvboxPurple' },
    CmpItemKindColor = { link = 'GruvboxPurple' },
    CmpItemKindSnippet = { link = 'GruvboxGreen' },
    CmpItemKindFile = { link = 'GruvboxBlue' },
    CmpItemKindFolder = { link = 'GruvboxBlue' },
    CmpItemKindEnumMember = { link = 'GruvboxAqua' },
    CmpItemKindConstant = { link = 'GruvboxOrange' },
    CmpItemKindStruct = { link = 'GruvboxYellow' },
    CmpItemKindTypeParameter = { link = 'GruvboxYellow' },
    diffAdded = { link = 'GruvboxGreen' },
    diffRemoved = { link = 'GruvboxRed' },
    diffChanged = { link = 'GruvboxAqua' },
    diffFile = { link = 'GruvboxOrange' },
    diffNewFile = { link = 'GruvboxYellow' },
    diffOldFile = { link = 'GruvboxOrange' },
    diffLine = { link = 'GruvboxBlue' },
    diffIndexLine = { link = 'diffChanged' },
    -- html
    htmlTag = { link = 'GruvboxAquaBold' },
    htmlEndTag = { link = 'GruvboxAquaBold' },
    htmlTagName = { link = 'GruvboxBlue' },
    htmlArg = { link = 'GruvboxOrange' },
    htmlTagN = { link = 'GruvboxFg1' },
    htmlSpecialTagName = { link = 'GruvboxBlue' },
    htmlLink = { fg = colors.fg4 },
    htmlSpecialChar = { link = 'GruvboxRed' },
    htmlBold = { fg = colors.fg0, bg = colors.bg0 },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0 },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0 },
    htmlUnderlineItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    -- xml
    xmlTag = { link = 'GruvboxAquaBold' },
    xmlEndTag = { link = 'GruvboxAquaBold' },
    xmlTagName = { link = 'GruvboxBlue' },
    xmlEqual = { link = 'GruvboxBlue' },
    docbkKeyword = { link = 'GruvboxAquaBold' },
    xmlDocTypeDecl = { link = 'GruvboxGray' },
    xmlDocTypeKeyword = { link = 'GruvboxPurple' },
    xmlCdataStart = { link = 'GruvboxGray' },
    xmlCdataCdata = { link = 'GruvboxPurple' },
    dtdFunction = { link = 'GruvboxGray' },
    dtdTagName = { link = 'GruvboxPurple' },
    xmlAttrib = { link = 'GruvboxOrange' },
    xmlProcessingDelim = { link = 'GruvboxGray' },
    dtdParamEntityPunct = { link = 'GruvboxGray' },
    dtdParamEntityDPunct = { link = 'GruvboxGray' },
    xmlAttribPunct = { link = 'GruvboxGray' },
    xmlEntity = { link = 'GruvboxRed' },
    xmlEntityPunct = { link = 'GruvboxRed' },
    -- clojure
    clojureKeyword = { link = 'GruvboxBlue' },
    clojureCond = { link = 'GruvboxOrange' },
    clojureSpecial = { link = 'GruvboxOrange' },
    clojureDefine = { link = 'GruvboxOrange' },
    clojureFunc = { link = 'GruvboxYellow' },
    clojureRepeat = { link = 'GruvboxYellow' },
    clojureCharacter = { link = 'GruvboxAqua' },
    clojureStringEscape = { link = 'GruvboxAqua' },
    clojureException = { link = 'GruvboxRed' },
    clojureRegexp = { link = 'GruvboxAqua' },
    clojureRegexpEscape = { link = 'GruvboxAqua' },
    clojureRegexpCharClass = { fg = colors.fg3 },
    clojureRegexpMod = { link = 'clojureRegexpCharClass' },
    clojureRegexpQuantifier = { link = 'clojureRegexpCharClass' },
    clojureParen = { link = 'GruvboxFg3' },
    clojureAnonArg = { link = 'GruvboxYellow' },
    clojureVariable = { link = 'GruvboxBlue' },
    clojureMacro = { link = 'GruvboxOrange' },
    clojureMeta = { link = 'GruvboxYellow' },
    clojureDeref = { link = 'GruvboxYellow' },
    clojureQuote = { link = 'GruvboxYellow' },
    clojureUnquote = { link = 'GruvboxYellow' },
    -- C
    cOperator = { link = 'GruvboxPurple' },
    cppOperator = { link = 'GruvboxPurple' },
    cStructure = { link = 'GruvboxOrange' },
    -- python
    pythonBuiltin = { link = 'GruvboxOrange' },
    pythonBuiltinObj = { link = 'GruvboxOrange' },
    pythonBuiltinFunc = { link = 'GruvboxOrange' },
    pythonFunction = { link = 'GruvboxAqua' },
    pythonDecorator = { link = 'GruvboxRed' },
    pythonInclude = { link = 'GruvboxBlue' },
    pythonImport = { link = 'GruvboxBlue' },
    pythonRun = { link = 'GruvboxBlue' },
    pythonCoding = { link = 'GruvboxBlue' },
    pythonOperator = { link = 'GruvboxRed' },
    pythonException = { link = 'GruvboxRed' },
    pythonExceptions = { link = 'GruvboxPurple' },
    pythonBoolean = { link = 'GruvboxPurple' },
    pythonDot = { link = 'GruvboxFg3' },
    pythonConditional = { link = 'GruvboxRed' },
    pythonRepeat = { link = 'GruvboxRed' },
    pythonDottedName = { link = 'GruvboxGreenBold' },
    -- CSS
    cssBraces = { link = 'GruvboxBlue' },
    cssFunctionName = { link = 'GruvboxYellow' },
    cssIdentifier = { link = 'GruvboxOrange' },
    cssClassName = { link = 'GruvboxGreen' },
    cssColor = { link = 'GruvboxBlue' },
    cssSelectorOp = { link = 'GruvboxBlue' },
    cssSelectorOp2 = { link = 'GruvboxBlue' },
    cssImportant = { link = 'GruvboxGreen' },
    cssVendor = { link = 'GruvboxFg1' },
    cssTextProp = { link = 'GruvboxAqua' },
    cssAnimationProp = { link = 'GruvboxAqua' },
    cssUIProp = { link = 'GruvboxYellow' },
    cssTransformProp = { link = 'GruvboxAqua' },
    cssTransitionProp = { link = 'GruvboxAqua' },
    cssPrintProp = { link = 'GruvboxAqua' },
    cssPositioningProp = { link = 'GruvboxYellow' },
    cssBoxProp = { link = 'GruvboxAqua' },
    cssFontDescriptorProp = { link = 'GruvboxAqua' },
    cssFlexibleBoxProp = { link = 'GruvboxAqua' },
    cssBorderOutlineProp = { link = 'GruvboxAqua' },
    cssBackgroundProp = { link = 'GruvboxAqua' },
    cssMarginProp = { link = 'GruvboxAqua' },
    cssListProp = { link = 'GruvboxAqua' },
    cssTableProp = { link = 'GruvboxAqua' },
    cssFontProp = { link = 'GruvboxAqua' },
    cssPaddingProp = { link = 'GruvboxAqua' },
    cssDimensionProp = { link = 'GruvboxAqua' },
    cssRenderProp = { link = 'GruvboxAqua' },
    cssColorProp = { link = 'GruvboxAqua' },
    cssGeneratedContentProp = { link = 'GruvboxAqua' },
    -- javascript
    javaScriptBraces = { link = 'GruvboxFg1' },
    javaScriptFunction = { link = 'GruvboxAqua' },
    javaScriptIdentifier = { link = 'GruvboxRed' },
    javaScriptMember = { link = 'GruvboxBlue' },
    javaScriptNumber = { link = 'GruvboxPurple' },
    javaScriptNull = { link = 'GruvboxPurple' },
    javaScriptParens = { link = 'GruvboxFg3' },
    -- typescript
    typescriptReserved = { link = 'GruvboxAqua' },
    typescriptLabel = { link = 'GruvboxAqua' },
    typescriptFuncKeyword = { link = 'GruvboxAqua' },
    typescriptIdentifier = { link = 'GruvboxOrange' },
    typescriptBraces = { link = 'GruvboxFg1' },
    typescriptEndColons = { link = 'GruvboxFg1' },
    typescriptDOMObjects = { link = 'GruvboxFg1' },
    typescriptAjaxMethods = { link = 'GruvboxFg1' },
    typescriptLogicSymbols = { link = 'GruvboxFg1' },
    typescriptDocSeeTag = { link = 'Comment' },
    typescriptDocParam = { link = 'Comment' },
    typescriptDocTags = { link = 'vimCommentTitle' },
    typescriptGlobalObjects = { link = 'GruvboxFg1' },
    typescriptParens = { link = 'GruvboxFg3' },
    typescriptOpSymbols = { link = 'GruvboxFg3' },
    typescriptHtmlElemProperties = { link = 'GruvboxFg1' },
    typescriptNull = { link = 'GruvboxPurple' },
    typescriptInterpolationDelimiter = { link = 'GruvboxAqua' },
    -- purescript
    purescriptModuleKeyword = { link = 'GruvboxAqua' },
    purescriptModuleName = { link = 'GruvboxFg1' },
    purescriptWhere = { link = 'GruvboxAqua' },
    purescriptDelimiter = { link = 'GruvboxFg4' },
    purescriptType = { link = 'GruvboxFg1' },
    purescriptImportKeyword = { link = 'GruvboxAqua' },
    purescriptHidingKeyword = { link = 'GruvboxAqua' },
    purescriptAsKeyword = { link = 'GruvboxAqua' },
    purescriptStructure = { link = 'GruvboxAqua' },
    purescriptOperator = { link = 'GruvboxBlue' },
    purescriptTypeVar = { link = 'GruvboxFg1' },
    purescriptConstructor = { link = 'GruvboxFg1' },
    purescriptFunction = { link = 'GruvboxFg1' },
    purescriptConditional = { link = 'GruvboxOrange' },
    purescriptBacktick = { link = 'GruvboxOrange' },
    -- coffescript
    coffeeExtendedOp = { link = 'GruvboxFg3' },
    coffeeSpecialOp = { link = 'GruvboxFg3' },
    coffeeCurly = { link = 'GruvboxOrange' },
    coffeeParen = { link = 'GruvboxFg3' },
    coffeeBracket = { link = 'GruvboxOrange' },
    -- ruby
    rubyStringDelimiter = { link = 'GruvboxGreen' },
    rubyInterpolationDelimiter = { link = 'GruvboxAqua' },
    rubyDefinedOperator = { link = 'rubyKeyword' },
    -- objc
    objcTypeModifier = { link = 'GruvboxRed' },
    objcDirective = { link = 'GruvboxBlue' },
    -- go
    goDirective = { link = 'GruvboxAqua' },
    goConstants = { link = 'GruvboxPurple' },
    goDeclaration = { link = 'GruvboxRed' },
    goDeclType = { link = 'GruvboxBlue' },
    goBuiltins = { link = 'GruvboxOrange' },
    -- lua
    luaIn = { link = 'GruvboxRed' },
    luaFunction = { link = 'GruvboxAqua' },
    luaTable = { link = 'GruvboxOrange' },
    -- moonscript
    moonSpecialOp = { link = 'GruvboxFg3' },
    moonExtendedOp = { link = 'GruvboxFg3' },
    moonFunction = { link = 'GruvboxFg3' },
    moonObject = { link = 'GruvboxYellow' },
    -- java
    javaAnnotation = { link = 'GruvboxBlue' },
    javaDocTags = { link = 'GruvboxAqua' },
    javaCommentTitle = { link = 'vimCommentTitle' },
    javaParen = { link = 'GruvboxFg3' },
    javaParen1 = { link = 'GruvboxFg3' },
    javaParen2 = { link = 'GruvboxFg3' },
    javaParen3 = { link = 'GruvboxFg3' },
    javaParen4 = { link = 'GruvboxFg3' },
    javaParen5 = { link = 'GruvboxFg3' },
    javaOperator = { link = 'GruvboxOrange' },
    javaVarArg = { link = 'GruvboxGreen' },
    -- elixir
    elixirDocString = { link = 'Comment' },
    elixirStringDelimiter = { link = 'GruvboxGreen' },
    elixirInterpolationDelimiter = { link = 'GruvboxAqua' },
    elixirModuleDeclaration = { link = 'GruvboxYellow' },
    -- scala
    scalaNameDefinition = { link = 'GruvboxFg1' },
    scalaCaseFollowing = { link = 'GruvboxFg1' },
    scalaCapitalWord = { link = 'GruvboxFg1' },
    scalaTypeExtension = { link = 'GruvboxFg1' },
    scalaKeyword = { link = 'GruvboxRed' },
    scalaKeywordModifier = { link = 'GruvboxRed' },
    scalaSpecial = { link = 'GruvboxAqua' },
    scalaOperator = { link = 'GruvboxFg1' },
    scalaTypeDeclaration = { link = 'GruvboxYellow' },
    scalaTypeTypePostDeclaration = { link = 'GruvboxYellow' },
    scalaInstanceDeclaration = { link = 'GruvboxFg1' },
    scalaInterpolation = { link = 'GruvboxAqua' },
    -- markdown
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3 },
    markdownBoldItalic = { fg = colors.fg3, italic = true },
    markdownH1 = { link = 'GruvboxGreenBold' },
    markdownH2 = { link = 'GruvboxGreenBold' },
    markdownH3 = { link = 'GruvboxYellowBold' },
    markdownH4 = { link = 'GruvboxYellowBold' },
    markdownH5 = { link = 'GruvboxYellow' },
    markdownH6 = { link = 'GruvboxYellow' },
    markdownCode = { link = 'GruvboxAqua' },
    markdownCodeBlock = { link = 'GruvboxAqua' },
    markdownCodeDelimiter = { link = 'GruvboxAqua' },
    markdownBlockquote = { link = 'GruvboxGray' },
    markdownListMarker = { link = 'GruvboxGray' },
    markdownOrderedListMarker = { link = 'GruvboxGray' },
    markdownRule = { link = 'GruvboxGray' },
    markdownHeadingRule = { link = 'GruvboxGray' },
    markdownUrlDelimiter = { link = 'GruvboxFg3' },
    markdownLinkDelimiter = { link = 'GruvboxFg3' },
    markdownLinkTextDelimiter = { link = 'GruvboxFg3' },
    markdownHeadingDelimiter = { link = 'GruvboxOrange' },
    markdownUrl = { link = 'GruvboxPurple' },
    markdownUrlTitleDelimiter = { link = 'GruvboxGreen' },
    markdownLinkText = { fg = colors.gray },
    markdownIdDeclaration = { link = 'markdownLinkText' },
    -- haskell
    haskellType = { link = 'GruvboxBlue' },
    haskellIdentifier = { link = 'GruvboxAqua' },
    haskellSeparator = { link = 'GruvboxFg4' },
    haskellDelimiter = { link = 'GruvboxOrange' },
    haskellOperators = { link = 'GruvboxPurple' },
    haskellBacktick = { link = 'GruvboxOrange' },
    haskellStatement = { link = 'GruvboxPurple' },
    haskellConditional = { link = 'GruvboxPurple' },
    haskellLet = { link = 'GruvboxRed' },
    haskellDefault = { link = 'GruvboxRed' },
    haskellWhere = { link = 'GruvboxRed' },
    haskellBottom = { link = 'GruvboxRedBold' },
    haskellImportKeywords = { link = 'GruvboxPurpleBold' },
    haskellDeclKeyword = { link = 'GruvboxOrange' },
    haskellDecl = { link = 'GruvboxOrange' },
    haskellDeriving = { link = 'GruvboxPurple' },
    haskellAssocType = { link = 'GruvboxAqua' },
    haskellNumber = { link = 'GruvboxAqua' },
    haskellPragma = { link = 'GruvboxRedBold' },
    haskellTH = { link = 'GruvboxAquaBold' },
    haskellForeignKeywords = { link = 'GruvboxGreen' },
    haskellKeyword = { link = 'GruvboxRed' },
    haskellFloat = { link = 'GruvboxAqua' },
    haskellInfix = { link = 'GruvboxPurple' },
    haskellQuote = { link = 'GruvboxGreenBold' },
    haskellShebang = { link = 'GruvboxYellowBold' },
    haskellLiquid = { link = 'GruvboxPurpleBold' },
    haskellQuasiQuoted = { link = 'GruvboxBlueBold' },
    haskellRecursiveDo = { link = 'GruvboxPurple' },
    haskellQuotedType = { link = 'GruvboxRed' },
    haskellPreProc = { link = 'GruvboxFg4' },
    haskellTypeRoles = { link = 'GruvboxRedBold' },
    haskellTypeForall = { link = 'GruvboxRed' },
    haskellPatternKeyword = { link = 'GruvboxBlue' },
    -- json
    jsonKeyword = { link = 'GruvboxGreen' },
    jsonQuote = { link = 'GruvboxGreen' },
    jsonBraces = { link = 'GruvboxFg1' },
    jsonString = { link = 'GruvboxFg1' },
    -- mail
    mailQuoted1 = { link = 'GruvboxAqua' },
    mailQuoted2 = { link = 'GruvboxPurple' },
    mailQuoted3 = { link = 'GruvboxYellow' },
    mailQuoted4 = { link = 'GruvboxGreen' },
    mailQuoted5 = { link = 'GruvboxRed' },
    mailQuoted6 = { link = 'GruvboxOrange' },
    mailSignature = { link = 'Comment' },
    -- c#
    csBraces = { link = 'GruvboxFg1' },
    csEndColon = { link = 'GruvboxFg1' },
    csLogicSymbols = { link = 'GruvboxFg1' },
    csParens = { link = 'GruvboxFg3' },
    csOpSymbols = { link = 'GruvboxFg3' },
    csInterpolationDelimiter = { link = 'GruvboxFg3' },
    csInterpolationAlignDel = { link = 'GruvboxAquaBold' },
    csInterpolationFormat = { link = 'GruvboxAqua' },
    csInterpolationFormatDel = { link = 'GruvboxAquaBold' },
    -- rust btw
    rustSigil = { link = 'GruvboxOrange' },
    rustEscape = { link = 'GruvboxAqua' },
    rustStringContinuation = { link = 'GruvboxAqua' },
    rustEnum = { link = 'GruvboxAqua' },
    rustStructure = { link = 'GruvboxAqua' },
    rustModPathSep = { link = 'GruvboxFg2' },
    rustCommentLineDoc = { link = 'Comment' },
    rustDefault = { link = 'GruvboxAqua' },
    -- ocaml
    ocamlOperator = { link = 'GruvboxFg1' },
    ocamlKeyChar = { link = 'GruvboxOrange' },
    ocamlArrow = { link = 'GruvboxOrange' },
    ocamlInfixOpKeyword = { link = 'GruvboxRed' },
    ocamlConstructor = { link = 'GruvboxOrange' },
  }
end

return M
