local topics = {
  ['notation'] = 'NOT',
  ['set_theory'] = 'SET',
  ['functions'] = 'FUN',
  ['group_theory'] = 'GRP',
  ['ring_theory'] = 'RNG',
  ['module_theory'] = 'MOD',
  ['polynomials'] = 'POL',
  ['real_analysis'] = 'REA',
  ['bartle_sherbert'] = 'BTS',
  ['linear_algebra'] = 'LNA',
  ['calculus'] = 'CAL',
  ['analysis'] = 'ALS',
  ['plenary'] = 'PLN',
  ['algorithm_design'] = 'ALD',
  ['parallel_programming'] = 'PAR',
  ['complex_analysis'] = 'CPA',
  ['functional_analysis'] = 'FNA',
  ['machine_learning'] = 'ML*',
  ['measure_theory'] = 'MST',
  ['numerical_analysis'] = 'NMA',
  ['nonlinear_optimization_unconstrained'] = 'NOU',
  ['nonlinear_optimization_constrained'] = 'NOC',
  ['ordinary_differential_equations'] = 'ODE',
  ['optimization'] = 'OPT',
  ['counting'] = 'CNT',
  ['statistics'] = 'STC',
  ['statistics_examples'] = 'STX',
  ['topology'] = 'TOP',
  ['fourier_analysis'] = 'FRA',
  ['sturm_liouville_theory'] = 'SLT',
  ['representation_theory'] = 'RPT',
  ['uatfo'] = 'UAT',
  ['errors'] = 'ERR',
  ['exercise'] = 'EXR',
  ['cheatsheet'] = 'CHT',
  ['ma3201'] = 'MA₁',
  ['ma3209'] = 'MA₉',
  ['ma3210'] = 'MA₀',
}
local marks = {
  'Definition',
  'Proposition',
  'Theorem',
  'Lemma',
  'Remark',
  'Result',
  'Corollary',
  'Algorithm',
  'Example',
  'Notation',
  'Problem',
  'Exercise',
  'Axiom',
  'Principle',
  'Scope',
  'Ansatz',
}
return { topics = topics, marks = marks }
