local topics = {
  ['notation'] = '*',
  ['set_theory'] = 'SET',
  ['functions'] = 'FUN',
  ['ring_theory'] = 'RING',
  ['group_theory'] = 'GRP',
  ['polynomials'] = 'POL',
  ['real_analysis'] = 'REA',
  ['linear_algebra'] = 'LNA',
  ['linear_algebra2'] = 'LNA2',
  ['calculus'] = 'CAL',
  ['plenary'] = 'PLN',
  ['algorithm_design'] = 'ALD',
  ['complex_analysis'] = 'CPA',
  ['functional_analysis'] = 'FNA',
  ['machine_learning'] = 'ML',
  ['measure_theory'] = 'MST',
  ['numerical_analysis'] = 'NMA',
  ['nonlinear_optimization_unconstrained'] = 'NOU',
  ['nonlinear_optimization_constrained'] = 'NOC',
  ['ordinary_differential_equations'] = 'ODE',
  ['optimization'] = 'OPT',
  ['counting'] = 'CNT',
  ['statistics'] = 'STC',
  ['statistics_examples'] = 'STX',
  ['topology'] = 'TOP',
  ['fourier_analysis'] = 'FRA',
  ['uatfo'] = 'UAT',
  ['errors'] = 'ERR',
}
local marks = {
  'Definition',
  'Proposition',
  'Theorem',
  'Lemma',
  'Remark',
  'Result',
  'Corollary',
  'Algorithm',
  'Example',
  'Notation',
  'Problem',
  'Exercise',
  'Axiom',
  'Principle',
  'Scope',
}
return { topics = topics, marks = marks }
