local topics = {
  ['defs/notation'] = '[d/*]',
  ['defs/set_theory'] = '[d/SET]',
  ['defs/ring_theory'] = '[d/RING]',
  ['defs/polynomials'] = '[d/POL]',
  ['defs/real_analysis'] = '[d/REA]',
  ['defs/linear_algebra'] = '[d/LNA]',
  ['defs/calculus'] = '[d/CAL]',
  ['defs/functional_analysis'] = '[d/FNA]',
  ['defs/measure_theory'] = '[d/MST]',
  ['defs/optimization'] = '[d/OPT]',
  ['defs/counting'] = '[d/CNT]',
  ['defs/topology'] = '[d/TOP]',
  ['core/set_theory'] = '[c/SET]',
  ['core/ring_theory'] = '[c/RING]',
  ['core/group_theory'] = '[c/GRP]',
  ['core/polynomials'] = '[c/POL]',
  ['core/real_analysis'] = '[c/REA]',
  ['core/linear_algebra'] = '[c/LNA]',
  ['core/functional_analysis'] = '[c/FNA]',
  ['core/measure_theory'] = '[c/MST]',
  ['core/counting'] = '[c/CNT]',
  ['core/topology'] = '[c/TOP]',
  ['lib/functions'] = '[l/FUN]',
  ['lib/real_analysis'] = '[l/REA]',
  ['lib/linear_algebra'] = '[l/LNA]',
  ['lib/linear_algebra2'] = '[l/LNA2]',
  ['lib/calculus'] = '[l/CAL]',
  ['lib/plenary'] = '[l/PLN]',
  ['lib/algorithm_design'] = '[l/ALD]',
  ['lib/complex_analysis'] = '[l/CPA]',
  ['lib/functional_analysis'] = '[l/FNA]',
  ['lib/machine_learning'] = '[l/ML]',
  ['lib/numerical_analysis'] = '[l/NMA]',
  ['lib/nonlinear_optimization_unconstrained'] = '[l/NOU]',
  ['lib/nonlinear_optimization_constrained'] = '[l/NOC]',
  ['lib/ordinary_differential_equations'] = '[l/ODE]',
  ['lib/statistics'] = '[l/STC]',
  ['lib/statistics_examples'] = '[l/STX]',
  ['lib/uatfo'] = '[l/UAT]',
  ['lib/errors'] = '[l/ERR]',
}
local marks = {
  'Definition',
  'Proposition',
  'Theorem',
  'Lemma',
  'Remark',
  'Result',
  'Corollary',
  'Algorithm',
  'Example',
  'Notation',
  'Problem',
  'Exercise',
  'Axiom',
  'Principle',
  'Scope',
}
return { topics = topics, marks = marks }
